### ISSUE TITLE
Missing DL4NTP Dataset

### ISSUE THREAD

**Issue by mikelegouva** [fle1scha/DL4NTP#6]
Hello . I am trying to replicate the training procedure but the dataset is missing . Is there anyway to access dataset?

**Comment by fle1scha** [comment]
Hey @mikelegouva. The dataset was given to us by SANREN. You can contact [jchavula@cs.uct.ac. za](mailto:jchavula@cs.uct.ac.%20za), who was the supervisor of my DL4NTP project.

**Comment by mikelegouva** [comment]
I sent a related email but received no response

**Comment by fle1scha** [comment]
I’m sorry, but there’s nothing I can to do help. You could use a different
dataset and apply the models and techniques from this project.

**Comment by fjxmdarek** [comment]
hi,it is ok that you inform me about the name of each column(what elements?)in SANREN.txt?.In that way I'll be able to fill my own data in to the datasheet while keeping your data on your own?THANKS!
